# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_invoice_constraint_chronology
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: account-financial-tools (8.0)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-30 16:31+0000\n"
"PO-Revision-Date: 2023-07-28 21:10+0000\n"
"Last-Translator: Ivorra78 <informatica@totmaterial.es>\n"
"Language-Team: Spanish (http://www.transifex.com/oca/OCA-account-financial-"
"tools-8-0/language/es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.17\n"

#. module: account_invoice_constraint_chronology
#: model:ir.model.fields,field_description:account_invoice_constraint_chronology.field_account_journal__check_chronology
msgid "Check Chronology"
msgstr "Comprobar Cronología"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting draft invoice dated before {date_invoice} "
"exists, please validate it first."
msgstr ""
"Conflicto en la cronología: Existe una factura borrador en conflicto con "
"fecha de factura anterior {date_invoice} , por favor valídala antes de "
"continuar."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting validated invoice dated after "
"{date_invoice} exists."
msgstr ""
"Conflicto en la cronología: Existe una factura validada en conflicto con "
"fecha de factura {date_invoice} posterior."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: An invoice with a higher number {highest_name} dated "
"before {date_invoice} exists."
msgstr ""
"Conflicto en la cronología: Existe una factura con un número superior "
"{highest_name} y con fecha de factura anterior {date_invoice}."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: Invoice {name} cannot be {time} invoice {inv_name}."
msgstr ""
"Conflicto de cronología: Invoice {name} cannot be {time} invoice {inv_name}."

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_journal
msgid "Journal"
msgstr "Diario"

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_move
msgid "Journal Entry"
msgstr "Asiento"

#, python-format
#~ msgid ""
#~ "Chronology Error. Please confirm older draft invoices before "
#~ "{date_invoice} and try again."
#~ msgstr ""
#~ "Error de cronología. Por favor valida los borradores de facturas "
#~ "anteriores a {date_invoice} e intenta de nuevo."

#, python-format
#~ msgid ""
#~ "Chronology Error. There exist at least one invoice with a later date to "
#~ "{date_invoice}."
#~ msgstr ""
#~ "Error de cronología. Existe al menos una factura con fecha posterior a "
#~ "{date_invoice}."

#~ msgid "Invoice"
#~ msgstr "Factura"
